# Generated by Django 4.1.5 on 2023-02-18 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otp',
            old_name='mobile',
            new_name='phone',
        ),
    ]
